### ISSUE TITLE
line breaks are removed from JSXText value

### ISSUE THREAD

**Issue by felixroos** [syntax-tree/estree-util-build-jsx#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

estree-util-build-jsx@2.2.0

### Steps to reproduce

Hi! Any line break inside a `JSXText`'s `value` will be gone after `buildJsx` transformed it to a `Literlal`, where the `value` will have no line breaks anymore. 

It also happens in this test: https://github.com/syntax-tree/estree-util-build-jsx/blob/76a366d6248c6f61410733710aaf607ee0d580fe/test.js#L809-L822

### Expected behavior

The line breaks "\n" should be still there after buildJsx modified the ast, as they are valuable information

### Actual behavior

The line breaks are removed

### Affected runtime and version

node@16.12

**Comment by wooorm** [comment]
I don’t think they should. [Babel](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DwQwfABARhBQEGM4QCbOAenEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D) and [TypeScript](https://www.typescriptlang.org/play?#code/DwQwfABARhBQEGM4QCbOAenEA) perform the same algorithm as is done here. I don’t see why we should diverge from other implementations.
