### ISSUE TITLE
extra spaces in jsx

### ISSUE THREAD

**Issue by jeetiss** [syntax-tree/estree-util-build-jsx#4]
### Steps to reproduce

transpile next code with `estree-util-build-jsx`

```jsx
const a = () => (
  <>
    <div>text</div>
    <div>
      text
    </div>
    <div>
      text{" "}
    </div>
  </>
)
```

### Expected behavior

```jsx
const a = () =>
  React.createElement(
    React.Fragment,
    null,
    React.createElement("div", null, "text"),
    React.createElement("div", null, "text"),
    React.createElement("div", null, "text", " ")
  );
```

### Actual behavior

```js
const a = () =>
  React.createElement(
    React.Fragment,
    null,
    React.createElement("div", null, "text"),
    React.createElement("div", null, " text"),
    React.createElement("div", null, " text", " ")
  );
```

[typescript](
https://www.typescriptlang.org/play?noLib=true#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2q8ycAvHABQCUHAfNxpw4AHn7CRYgCbAAbvxhYAHjFEB6WQskjRWiVKlLVOsZvkGpei6ZHGYAbwBEcJwF9TG-ZI0SeQA), [babel](
https://babeljs.io/repl#?browsers=and_chr%2097%2C%20android%2093%2C%20chrome%2094%2C%20chrome%2093%2C%20chrome%2092%2C%20chrome%2091%2C%20chrome%2090%2C%20chrome%2089%2C%20chrome%2088%2C%20chrome%2087%2C%20chrome%2086%2C%20chrome%2070%2C%20edge%2094%2C%20edge%2093%2C%20edge%2092%2C%20edge%2091%2C%20edge%2018%2C%20firefox%2092%2C%20firefox%2091%2C%20firefox%2090%2C%20firefox%2089%2C%20firefox%2078%2C%20ios_saf%2015%2C%20ios_saf%2014.5-14.7%2C%20ios_saf%2014.0-14.4%2C%20ios_saf%2013.4-13.7%2C%20opera%2078%2C%20opera%2077%2C%20opera%2076%2C%20safari%2015%2C%20safari%2014.1%2C%20safari%2014%2C%20safari%2013.1%2C%20safari%2013%2C%20safari%2012.1&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBAhjAvDAFASiQPlQKBjAHkz30IBMBLAN0ygFMAPKAgekppPwPeNNPqadCbar1LdRQ_AKgBvAEQx5AXyGseJVsTRA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact&prettier=true&targets=&version=7.20.11&externalPlugins=&assumptions=%7B%7D), [swc](
https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA0vOzysuUUhUsFXQ0FSwtVPQ4FJQsLEDEkAqJbPMriS1osRGH8RCiIFZCgogKYggbvlqJQWlWlRFNvp2XJoASKE%2BBncAAAA%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE7zJrb9uF79BDCFcJLv4hOVBjfPfaISU7MfPmoY6POtiOQqIs69KWKn1hwS6SOvGlwkxsRlUOHgaVZOe6CH3MKuSsDLtRUDaIPvmtLZHLsQir3hWlPfzJMUUxv48VdNRW%2BBQ%2BMW7HtfP6usDzgR%2Fs3ILttAAAAA%3D%3D) work as expected, but this project adds extra leading spaces

**Comment by wooorm** [comment]
Why should this project do things differently than babel, esbuild, typescript, swc?

**Comment by jeetiss** [comment]
Babel and typescript don't add spaces in this case (don't have exp with esbuild and swc)

check the [repl](https://babeljs.io/repl#?browsers=and_chr%2097%2C%20android%2093%2C%20chrome%2094%2C%20chrome%2093%2C%20chrome%2092%2C%20chrome%2091%2C%20chrome%2090%2C%20chrome%2089%2C%20chrome%2088%2C%20chrome%2087%2C%20chrome%2086%2C%20chrome%2070%2C%20edge%2094%2C%20edge%2093%2C%20edge%2092%2C%20edge%2091%2C%20edge%2018%2C%20firefox%2092%2C%20firefox%2091%2C%20firefox%2090%2C%20firefox%2089%2C%20firefox%2078%2C%20ios_saf%2015%2C%20ios_saf%2014.5-14.7%2C%20ios_saf%2014.0-14.4%2C%20ios_saf%2013.4-13.7%2C%20opera%2078%2C%20opera%2077%2C%20opera%2076%2C%20safari%2015%2C%20safari%2014.1%2C%20safari%2014%2C%20safari%2013.1%2C%20safari%2013%2C%20safari%2012.1&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBAhjAvDAFASiQPlQKBjAHkz30IBMBLAN0ygFMAPKAgekppPwPeNNPqadCbar1LdRQ_AKgBvAEQx5AXyGseJVsTRA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact&prettier=true&targets=&version=7.20.11&externalPlugins=&assumptions=%7B%7D) 

EDIT:

[swc trims leading spaces too](https://play.swc.rs/?version=1.3.24&code=H4sIAAAAAAAAA0vOzysuUUhUsFXQ0FSwtVPQ4FJQsLEDEkAqJbPMriS1osRGH8RCiIFZCgogKYggbvlqJQWlWlRFNvp2XJoASKE%2BBncAAAA%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE7zJrb9uF79BDCFcJLv4hOVBjfPfaISU7MfPmoY6POtiOQqIs69KWKn1hwS6SOvGlwkxsRlUOHgaVZOe6CH3MKuSsDLtRUDaIPvmtLZHLsQir3hWlPfzJMUUxv48VdNRW%2BBQ%2BMW7HtfP6usDzgR%2Fs3ILttAAAAA%3D%3D).
